### ISSUE TITLE
New functions in GUI

### ISSUE THREAD

**Issue by pavolgaj** [pavolgaj/OCFit#4]
Add function to calculate m3sin(i) and m4sin(i) for LiTE models.

GUI - add the button to call the function `AbsoluteParam` and the new function for m*sin(i).

**Comment by pavolgaj** [comment]
Remember the values set in FitParams and set it after reopening this window. 

Fixed by https://github.com/pavolgaj/OCFit/commit/01363802f6cf2d9e3f7f5bba636598d38e2c524f

**Comment by HeBe-lab** [comment]
Hello teacher,I would like to ask you about this article"NEW TOOL WITH GUI FOR FITTING O-C DIAGRAMS"How are the values of such parameters as Q,a_sin_i3,e3,w3,t03,p3 obtained in?

**Comment by pavolgaj** [comment]
Fixed by https://github.com/pavolgaj/OCFit/commit/01363802f6cf2d9e3f7f5bba636598d38e2c524f and https://github.com/pavolgaj/OCFit/commit/82155fcb7d020fb6e681d02e11dd8c53512c54bc
