### ISSUE TITLE
pymc required?

### ISSUE THREAD

**Issue by selseyastro** [pavolgaj/OCFit#6]
I have tried running OCFit but it requires pymc. So tried installing pymc but not possible as it needs a Fortran compiler??

Regards,
John

**Comment by pavolgaj** [comment]
Hi,
NO, pymc is not required but only highly recommended. You can use OCFit also without pymc but you can't use functions `FitMCMC `and `InfoMCMC`. Fitting with GA will be the only possibility.

Which OS do you use? Installing pymc on Windows is quite complicated - you can try it: [https://github.com/pymc-devs/pymc/wiki/Building-PyMC-from-source-on-Windows](https://github.com/pymc-devs/pymc/wiki/Building-PyMC-from-source-on-Windows) 
You can also try compiled GUI for Windows: [https://github.com/pavolgaj/OCFit/releases/download/0.1.2-alpha/ocfit-gui-win.zip](https://github.com/pavolgaj/OCFit/releases/download/0.1.2-alpha/ocfit-gui-win.zip) It doesn't need python at all.

**Comment by pavolgaj** [comment]
> _From issue #7:_
So I installed gfortran and it is there! In C:/MinGW/bin/gfortran
Now try and install pymc and error is fortran compiler missing???
Said it had Fortran sources but no compiler.
What is going on??
And I was trying to help a fellow astronomer in our team who needs to use Ocfit.
Regards
John

Do you use python 2 or 3? I installed pymc on py2 under win successfully but not on py3. I use the mention steps: [https://github.com/pymc-devs/pymc/wiki/Building-PyMC-from-source-on-Windows](https://github.com/pymc-devs/pymc/wiki/Building-PyMC-from-source-on-Windows) You need to add the name of compiler to distutils.cfg file (step 7). I also add MinGW and MSys to 'Path' environment variable (similar to step 6).
Could you copy here a full error message?

P.S. John, please, use this conversation about this problem and not create new issues.
